
# Book settings
title: Mental Health Treatment Prediction
author: Ashish ashreepr 50607545
logo: logo.png
exclude_patterns: []

# Execution settings
execute:
  execute_notebooks: force

# HTML-specific settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  navbar_number_sections: true
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: "classic"
  binderhub_url: ""

repository:
  url: https://github.com/AshishS25/mental-health-app
  branch: main


